apiVersion: v1
kind: Service
metadata:
  name: cust-service
  namespace: cust
spec:
  selector:
    app: react
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30090
  type: NodePort

